<p> 
	<?php 
	printf( __( 'This page is generated by the %s plugin.', 'custom-post-type-date-archives' ), '<a href="https://wordpress.org/plugins/custom-post-type-date-archives/">' . __( 'Custom Post Type Date Archives', 'custom-post-type-date-archives') . '</a>' );
	?>
</p>