<h3>
	<?php _e( 'Add date archives', 'custom-post-type-date-archives' ); ?>
</h3>
<p>
	<?php printf( __( 'Add date archives to the custom post type %s.', 'custom-post-type-date-archives' ), $label ); ?>
</p>
<p>
	<?php _e( 'Example date archive url', 'custom-post-type-date-archives' ); ?><br/>
	<code><?php echo $sample_day_link; ?></code>
</p>
<h3>
	<?php _e( 'Publish posts with future dates', 'custom-post-type-date-archives' ); ?>
</h3>

<p>
	<?php _e( "Scheduled posts are posts with a future date that usually don't show up in the front of your site. This checkbox allows you to have scheduled posts display the same as normal published posts.", 'custom-post-type-date-archives' ); ?>
	<?php _e( 'If checked, <strong>new scheduled posts</strong> will be automatically published instead of scheduled.', 'custom-post-type-date-archives'); ?>
	<?php _e( 'To publish existing scheduled posts see the documentation below', 'custom-post-type-date-archives'); ?>
</p>

<ul>
	<li><a href="https://github.com/keesiemeijer/custom-post-type-date-archives/wiki/Scheduled-Posts#update-scheduled-posts-with-post-status-published"><?php _e('Publish existing scheduled posts', 'custom-post-type-date-archives'); ?></a></li>
</ul>

<p>
<?php _e( "Unchecking this setting doesn't automatically reschedule published posts with future dates.", 'custom-post-type-date-archives'); ?> 
<?php _e( 'To do just that see the documentation below.', 'custom-post-type-date-archives' ); ?>
</p>

<ul>
	<li><a href="https://github.com/keesiemeijer/custom-post-type-date-archives/wiki/Scheduled-Posts#reschedule-published-posts-with-a-future-date"><?php _e('Reschedule published posts with future dates', 'custom-post-type-date-archives'); ?></a></li>
</ul><br/>

<hr>

<h4>
	<?php printf( __( 'This help section is generated by the %s plugin.', 'custom-post-type-date-archives' ), '<a href="https://wordpress.org/plugins/custom-post-type-date-archives/">' . __( 'Custom Post Type Date Archives', 'custom-post-type-date-archives' ) . '</a>' ); ?><br/>
</h4>
