<p> 
	<?php _e( 'This page is generated by the Custom Post Type Date Archives plugin.', 'custom-post-type-date-archives' ); ?><br/>
	<a href="https://github.com/keesiemeijer/custom-post-type-date-archives/wiki"><?php _e( 'Plugin Documentation', 'custom-post-type-date-archives' ) ?></a>
</p>