<h4>
	<?php _e( 'This help section is generated by the Custom Post Type Date Archives plugin.', 'custom-post-type-date-archives' ); ?>
</h4>
<p>
	<?php printf( __( 'Add date archives to the custom post type %s.', 'custom-post-type-date-archives' ), $label ); ?>
</p>
<p>
	<?php _e( 'Example date archive url', 'custom-post-type-date-archives' ); ?><br/>
	<code><?php echo $sample_day_link ?></code>
</p>
<h4>
	<?php _e( 'Scheduled Posts', 'custom-post-type-date-archives' ); ?>
</h4>

<p>
	<?php _e( "Scheduled posts normally don't show up in the front of your site. If you've checked \"Publish posts with future dates\" newly published posts with a scheduled future date will be automatically published instead of scheduled.", 'custom-post-type-date-archives' ); ?>
</p>

<p>
	<?php printf( __( "See the %s for more information about scheduled posts and how to publish <strong>existing</strong> scheduled posts.", 'custom-post-type-date-archives' ), $scheduled_posts ); ?>
</p>
